import type { OptionLeg, TradeSimulation } from "@/types/domain";
import type { SaxoOptionPremiumCandidate } from "@/features/saxo/saxoAccountSync";
import { buildSaxoOptionValueSnapshot, upsertOptionValueSnapshot } from "@/domain/optionValueSnapshot";
import { getOperationalRemainingOptionLegs } from "@/domain/optionCloseExecutions";
import type { StockQuote } from "@/lib/marketData";

export type CurrentOptionPriceTarget = { targetId: string; simulationId: string; legId: string; ticker: string; strategyType: TradeSimulation["strategyType"]; optionType: OptionLeg["type"]; side: OptionLeg["side"]; strike: number; expiry: string; quantity: number; savedPriceUSD?: number; accountKey?: string; uic?: number; positionId?: string; instrumentCode?: string };
export type CurrentOptionPricePreviewRow = { target: CurrentOptionPriceTarget; candidate?: SaxoOptionPremiumCandidate; selectedPriceUSD?: number; selectedField?: "bid" | "ask"; status: "ready" | "confirmable_reference" | "unavailable"; reason: string };
export type CurrentStockPricePreviewRow = { ticker: string; simulationIds: string[]; savedPricesBySimulationId: Record<string, number | undefined>; quote?: StockQuote; status: "ready" | "unavailable"; reason: string };

const positive = (value: number | undefined) => value !== undefined && Number.isFinite(value) && value > 0 ? value : undefined;
export type SaxoOptionLegIdentifiers = { accountKey?: string; uic?: number; positionId?: string; instrumentCode?: string };
export function resolveSaxoOptionLegIdentifiers(simulation: TradeSimulation, leg: OptionLeg): SaxoOptionLegIdentifiers { const fixture = simulation.fixtureMeta; const legacyStandalone = simulation.optionLegs?.length === undefined || simulation.optionLegs.length === 1; return { accountKey: leg.saxoAccountKey ?? fixture?.saxoAccountKey, uic: leg.saxoUic ?? (legacyStandalone ? fixture?.saxoUic : undefined), positionId: leg.saxoPositionId ?? (legacyStandalone ? fixture?.saxoPositionId : undefined), instrumentCode: leg.brokerSymbol ?? (legacyStandalone ? fixture?.saxoInstrumentCode : undefined) }; }
export function getCurrentOptionPriceTargets(simulations: TradeSimulation[]): CurrentOptionPriceTarget[] { return simulations.flatMap((simulation) => simulation.status !== "open" ? [] : getOperationalRemainingOptionLegs(simulation).filter(({ leg }) => positive(leg.quantity) !== undefined).map(({ leg, progress }) => ({ targetId: `${simulation.id}:${leg.id}`, simulationId: simulation.id, legId: leg.id, ticker: simulation.ticker, strategyType: simulation.strategyType, optionType: leg.type, side: leg.side, strike: leg.strikeUSD, expiry: leg.expiryDate, quantity: progress.remainingContracts!, savedPriceUSD: positive(leg.closeCostUSD) ?? positive(leg.closePlan?.closePriceUSD), ...resolveSaxoOptionLegIdentifiers(simulation, leg) }))); }
export function selectSideAwarePremiumCandidate(candidate: SaxoOptionPremiumCandidate | undefined, side: OptionLeg["side"]): Pick<CurrentOptionPricePreviewRow, "selectedPriceUSD" | "selectedField" | "status" | "reason"> { if (!candidate || candidate.status !== "available") return { status: "unavailable", reason: candidate?.classification ?? "取得失敗" }; const field = side === "buy" ? "bid" : "ask"; const price = candidate[field]; const priceType = field === "bid" ? candidate.quoteDiagnostics?.priceTypeBid : candidate.quoteDiagnostics?.priceTypeAsk; if (["NoAccess", "NoMarket", "Pending"].includes(priceType ?? "")) return { status: "unavailable", reason: `${field === "bid" ? "Bid" : "Ask"}は${priceType}のため反映できません` }; if (priceType === "OldIndicative") return positive(price) === undefined ? { status: "unavailable", reason: `${field === "bid" ? "Bid" : "Ask"}が未取得` } : { selectedPriceUSD: price, selectedField: field, status: "confirmable_reference", reason: `${field === "bid" ? "Bid" : "Ask"}はOldIndicative（取得時点の参考値・確認が必要）` }; if (positive(price) !== undefined) return { selectedPriceUSD: price, selectedField: field, status: "ready", reason: side === "buy" ? "売却候補のBidを採用" : "買戻し候補のAskを採用" }; return { status: "unavailable", reason: [candidate.mid, candidate.last].some(positive) ? `${field === "bid" ? "Bid" : "Ask"}未取得（Mid/Lastは参考値のみ）` : `${field === "bid" ? "Bid" : "Ask"}未取得` }; }
export function createCurrentOptionPricePreviewRow(target: CurrentOptionPriceTarget, candidate?: SaxoOptionPremiumCandidate): CurrentOptionPricePreviewRow { return { target, candidate, ...selectSideAwarePremiumCandidate(candidate, target.side) }; }
export function getCurrentStockPriceTargets(simulations: TradeSimulation[]): Array<{ ticker: string; simulationIds: string[]; savedPricesBySimulationId: Record<string, number | undefined> }> { const grouped=new Map<string,{simulationIds:string[];savedPricesBySimulationId:Record<string,number|undefined>}>();for(const simulation of simulations){if(simulation.status!=="open")continue;const ticker=simulation.ticker.trim().toUpperCase();if(!ticker)continue;const current=grouped.get(ticker)??{simulationIds:[],savedPricesBySimulationId:{}};current.simulationIds.push(simulation.id);current.savedPricesBySimulationId[simulation.id]=Number.isFinite(simulation.currentPriceUSD)?simulation.currentPriceUSD:undefined;grouped.set(ticker,current);}return Array.from(grouped,([ticker,target])=>({ticker,...target})); }
export function createCurrentStockPricePreviewRow(target:{ticker:string;simulationIds:string[];savedPricesBySimulationId:Record<string,number|undefined>},quote?:StockQuote,error?:string):CurrentStockPricePreviewRow { if(!quote||quote.symbol.trim().toUpperCase()!==target.ticker||!Number.isFinite(quote.price)||quote.price<=0)return {...target,status:"unavailable",reason:error??"現在株価を取得できません"};return {...target,quote,status:"ready",reason:"取得済み（日次・遅延値の可能性あり）"}; }
export type BulkOptionPricePreviewCounts = { successful: number; ready: number; confirmableReference: number; unavailable: number };
export function getBulkOptionPricePreviewCounts(rows: CurrentOptionPricePreviewRow[]): BulkOptionPricePreviewCounts { const ready = rows.filter((row) => row.status === "ready").length; const confirmableReference = rows.filter((row) => row.status === "confirmable_reference").length; return { successful: ready + confirmableReference, ready, confirmableReference, unavailable: rows.length - ready - confirmableReference }; }
export function getBulkApplicableTargetIds(rows: CurrentOptionPricePreviewRow[], simulations: TradeSimulation[], includeConfirmedReferences = false): Set<string> { const ids = new Set(rows.filter((row) => (row.status === "ready" || (includeConfirmedReferences && row.status === "confirmable_reference")) && row.selectedPriceUSD !== undefined).map((row) => row.target.targetId)); for (const simulation of simulations) { if (simulation.strategyType !== "synthetic_forward" && simulation.strategyType !== "bear_put_spread") continue; const legIds = getOperationalRemainingOptionLegs(simulation).map(({ leg }) => `${simulation.id}:${leg.id}`); if (legIds.length > 0 && legIds.some((id) => !ids.has(id))) legIds.forEach((id) => ids.delete(id)); } return ids; }
export function applyCurrentOptionPricePreview(simulations: TradeSimulation[], rows: CurrentOptionPricePreviewRow[], options: { includeConfirmedReferences?: boolean; capturedAt?: string } = {}): TradeSimulation[] { const includeConfirmedReferences=options.includeConfirmedReferences??false;const capturedAt=options.capturedAt??new Date().toISOString();const applicable=getBulkApplicableTargetIds(rows,simulations,includeConfirmedReferences);const currentTargets=new Map(getCurrentOptionPriceTargets(simulations).map(target=>[target.targetId,target]));const update=new Map(rows.filter(row=>{const current=currentTargets.get(row.target.targetId);return applicable.has(row.target.targetId)&&row.selectedPriceUSD!==undefined&&current!==undefined&&current.quantity===row.target.quantity&&current.side===row.target.side&&current.optionType===row.target.optionType&&current.strike===row.target.strike&&current.expiry===row.target.expiry&&current.savedPriceUSD===row.target.savedPriceUSD;}).map(row=>[row.target.targetId,row]));return simulations.map(simulation=>{const optionLegs=simulation.optionLegs.map(leg=>{const row=update.get(`${simulation.id}:${leg.id}`);if(!row||row.selectedPriceUSD===undefined||!row.selectedField)return leg;const snapshot=leg.side==="buy"?buildSaxoOptionValueSnapshot(simulation,leg,row.selectedPriceUSD,row.candidate?.fetchedAt??capturedAt):null;const valueSnapshots=snapshot?upsertOptionValueSnapshot(leg.valueSnapshots,snapshot):leg.valueSnapshots;const priceType=row.selectedField==="bid"?row.candidate?.quoteDiagnostics?.priceTypeBid:row.candidate?.quoteDiagnostics?.priceTypeAsk;return {...leg,closeCostUSD:row.selectedPriceUSD,closePlan:{enabled:true,...(leg.closePlan??{}),closePriceUSD:row.selectedPriceUSD,priceSource:"saxo" as const,priceSelectedField:row.selectedField,priceFetchedAt:row.candidate?.fetchedAt??capturedAt,priceQuoteStatus:row.candidate?.status,priceType,priceReferenceConfirmed:row.status==="confirmable_reference"?true:undefined,priceReferenceConfirmedAt:row.status==="confirmable_reference"?capturedAt:undefined},valueSnapshots};});return optionLegs.every((leg,i)=>leg===simulation.optionLegs[i])?simulation:{...simulation,optionLegs};}); }
export function applyCurrentPricePreview(simulations:TradeSimulation[],optionRows:CurrentOptionPricePreviewRow[],stockRows:CurrentStockPricePreviewRow[],options:{includeConfirmedReferences?:boolean;capturedAt?:string}={}):TradeSimulation[]{const withOptions=applyCurrentOptionPricePreview(simulations,optionRows,options);const stocks=new Map(stockRows.filter(row=>row.status==="ready"&&row.quote).map(row=>[row.ticker,row]));return withOptions.map(simulation=>{if(simulation.status!=="open")return simulation;const row=stocks.get(simulation.ticker.trim().toUpperCase());if(!row?.quote||!row.simulationIds.includes(simulation.id)||simulation.currentPriceUSD!==row.savedPricesBySimulationId[simulation.id]||simulation.currentPriceUSD===row.quote.price)return simulation;return {...simulation,currentPriceUSD:row.quote.price};});}
