import { describe, expect, it } from 'vitest';
import type { TradeSimulation } from '@/types/domain';
import { buildOptionValueObservation, resolveOptionValueEvidenceRevision } from './timeValue';
import { recordParentTimeValueObservation } from './timeValueParent';

function fixture(credit = false): TradeSimulation {
  const sim: TradeSimulation = { id: 'test', ticker: 'TEST', name: 'anonymous', strategyType: credit ? 'bear_call_spread' : 'bull_call_spread', status: 'open', accountCode: 'N', accountCurrency: 'USD', accountEnvironment: 'PROD_N_USD_SETTLEMENT', currentPriceUSD: 110, fxRateJPY: 150, entryDate: '2026-09-01', expiryDate: '2026-12-18', dte: 86, stockPosition: null, brokerMarginJPY: 0, marginBufferMultiplier: 1, denominatorMode: 'custom', taxProfileId: 'none_nisa_or_tax_free_comparison', strategyContractVerification: { state: 'verified' }, optionLegs: [{ id: 'low', type: 'call', side: credit ? 'sell' : 'buy', strikeUSD: 100, premiumUSD: 11, quantity: 1, contractSize: 100, expiryDate: '2026-12-18', closePlan: { enabled: true, closePriceUSD: 13, commissionUSD: 2, commissionSource: 'manual', commissionContracts: 1 } }, { id: 'high', type: 'call', side: credit ? 'buy' : 'sell', strikeUSD: 120, premiumUSD: 3, quantity: 1, contractSize: 100, expiryDate: '2026-12-18', closePlan: { enabled: true, closePriceUSD: 3, commissionUSD: 2, commissionSource: 'manual', commissionContracts: 1 } }] };
  sim.optionEntryExecutions = sim.optionLegs.map(leg => ({ id: `entry-${leg.id}`, legId: leg.id, tradeDate: '2026-09-01', contracts: 1, fillPriceUSD: leg.premiumUSD, commissionUSD: 2, settlementCurrency: 'USD' as const, confirmed: true, source: 'broker_statement' as const }));
  reflect(sim, 'b1', '2026-09-23'); return sim;
}
function reflect(sim: TradeSimulation, batchId: string, date: string) { sim.optionLegs = sim.optionLegs.map(leg => ({ ...leg, valueObservations: [buildOptionValueObservation({ observationId: `${batchId}:${leg.id}`, batchId, snapshotDate: date, legId: leg.id, side: leg.side, optionType: leg.type, strikeUSD: leg.strikeUSD, expiry: leg.expiryDate, quantity: leg.quantity, contractSize: leg.contractSize!, optionPriceUSD: leg.closePlan!.closePriceUSD!, underlyingPriceUSD: 110, source: 'saxo', selectedField: leg.side === 'buy' ? 'bid' : 'ask', feeUSD: 2, feeSource: 'manual', evidenceRevision: resolveOptionValueEvidenceRevision({ legId: leg.id, entryExecutions: sim.optionEntryExecutions, closeExecutions: sim.optionCloseExecutions }) })!] })); }
describe('R14 independent fixed parent arithmetic', () => {
  it('retains bull-call V1000/CF996/PnL192', () => expect(recordParentTimeValueObservation(fixture(), [], 'b1').observations[0]).toMatchObject({ positionValueUSD: 1000, intrinsicValueUSD: 1000, timeValueUSD: 0, closeFeeUSD: 4, closeCashflowUSD: 996, estimatedPnlUSD: 192, synchronized: false }));
  it('retains credit V-1000/CF-1004/PnL-208', () => expect(recordParentTimeValueObservation(fixture(true), [], 'b1').observations[0]).toMatchObject({ positionValueUSD: -1000, intrinsicValueUSD: -1000, closeCashflowUSD: -1004, estimatedPnlUSD: -208 }));
  it('preserves immutable prior batch after one leg fails', () => { const sim = fixture(), first = recordParentTimeValueObservation(sim, [], 'b1').observations; sim.optionLegs[0].valueObservations![0].batchId = 'b2'; const result = recordParentTimeValueObservation(sim, first, 'b2'); expect(result.updated).toBe(false); expect(result.observations).toBe(first); expect(first[0].legs[0].batchId).toBe('b1'); });
  it('keeps distinct dates with the same accounting evidence', () => { const sim = fixture(), first = recordParentTimeValueObservation(sim, [], 'b1').observations; reflect(sim, 'b2', '2026-09-24'); expect(recordParentTimeValueObservation(sim, first, 'b2').observations).toHaveLength(2); });
  it('keeps original 192 beside corrected 191 after a one-dollar fee correction', () => { const sim = fixture(), first = recordParentTimeValueObservation(sim, [], 'b1').observations; sim.optionEntryExecutions![0].commissionUSD = 3; expect(recordParentTimeValueObservation(sim, first, 'b1').updated).toBe(false); reflect(sim, 'b2', '2026-09-23'); const corrected = recordParentTimeValueObservation(sim, first, 'b2').observations[0]; expect(corrected.evidenceChanged).toBe(true); expect(corrected.estimatedPnlUSD).toBe(191); expect(corrected.superseded?.[0].estimatedPnlUSD).toBe(192); });
  it('does not fabricate decomposition or net cashflow when price integrity or fees are missing', () => { const sim = fixture(); sim.optionLegs[0].closePlan!.closePriceUSD = 2; reflect(sim, 'b2', '2026-09-23'); sim.optionLegs[0].valueObservations![0].feeUSD = undefined; const result = recordParentTimeValueObservation(sim, [], 'b2').observations[0]; expect(result.positionValueUSD).toBe(-100); expect(result.timeValueUSD).toBeUndefined(); expect(result.closeCashflowUSD).toBeUndefined(); expect(result.estimatedPnlUSD).toBeUndefined(); });
});
